-- 繰り返し設定テーブルの作成
CREATE TABLE RECURRING_SETTINGS (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id INT REFERENCES "STAFF"(staff_id) NOT NULL,
  title TEXT NOT NULL,
  content TEXT,
  category_id INT REFERENCES "CATEGORY"(category_id),
  is_urgent BOOLEAN DEFAULT false,
  bounty_points INT,
  deadline_interval INT, -- 期限までの日数（もしあれば）
  
  recurrence_type TEXT NOT NULL, -- 'daily', 'weekly', 'monthly', 'yearly', 'custom'
  recurrence_config JSONB NOT NULL, -- 詳しい設定内容
  
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  
  is_active BOOLEAN DEFAULT true,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- DIARYテーブルに参照カラムを追加
ALTER TABLE "DIARY" ADD COLUMN recurring_id BIGINT REFERENCES RECURRING_SETTINGS(id);

-- インデックス作成（検索高速化のため）
CREATE INDEX idx_diary_recurring_id ON "DIARY"(recurring_id);
CREATE INDEX idx_recurring_settings_staff_id ON RECURRING_SETTINGS(staff_id);
